In [4]:
import numpy as np
A = np.array([[2,  1],
              [1, -1]])

b = np.array([10, 2])

In [6]:
print("Solutiona:", np.linalg.solve(A, b))


Solutiona: [4. 2.]


In [8]:
a_inv = np.linalg.inv(A)

In [10]:
a_inv

array([[ 0.33333333,  0.33333333],
       [ 0.33333333, -0.66666667]])

In [14]:
sol = a_inv.dot(b)

In [16]:
sol

array([4., 2.])

In [18]:
A.dot(sol)

array([10.,  2.])